#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Tests for agent/prov.py + tools/export_prov.py — W3C PROV export (Stage B).

Falsifiable invariants:
  1. Every claim becomes a PROV Entity + a Verification Activity, generated by it.
  2. Sources become Source entities the activity 'used'; parents become
     wasDerivedFrom edges.
  3. A claim with no claim_id is dropped (fail-closed: no anonymous lineage node).
  4. The produced document passes structural validation (no dangling references).
  5. PROV-N and PROV-JSON are both well-formed and round-trippable through json.
  6. The export CLI integrates with a real contract store.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.prov import claims_to_prov, to_prov_json, to_prov_n, validate_prov  # noqa: E402

CLAIMS = [
    {"claim_id": "c1", "content": "Laozi attributed author of Dao De Jing.",
     "sources": ["wikidata"], "parents": [], "blp_level": "UNCLASSIFIED",
     "created_at": "t0", "signature": "sig_a"},
    {"claim_id": "c2", "content": "derived claim", "sources": ["kb"],
     "parents": ["c1"], "blp_level": "CONFIDENTIAL", "created_at": "t1"},
]


def test_each_claim_is_entity_and_activity() -> None:
    doc = claims_to_prov(CLAIMS)
    assert "sophia:claim.c1" in doc["entity"]
    assert "sophia:claim.c2" in doc["entity"]
    assert "sophia:verify.c1" in doc["activity"]
    gen = list(doc["wasGeneratedBy"].values())
    pairs = {(g["prov:entity"], g["prov:activity"]) for g in gen}
    assert ("sophia:claim.c1", "sophia:verify.c1") in pairs


def test_sources_used_and_parents_derived() -> None:
    doc = claims_to_prov(CLAIMS)
    assert "sophia:source.wikidata" in doc["entity"]
    used_entities = {u["prov:entity"] for u in doc["used"].values()}
    assert "sophia:source.wikidata" in used_entities
    derived = {(d["prov:generatedEntity"], d["prov:usedEntity"])
               for d in doc["wasDerivedFrom"].values()}
    assert ("sophia:claim.c2", "sophia:claim.c1") in derived  # parent edge


def test_claim_without_id_is_dropped_failclosed() -> None:
    doc = claims_to_prov([{"content": "no id", "sources": ["x"]}])
    # only the recorder agent exists; no entities minted for an unidentified claim
    assert doc["entity"] == {}


def test_document_validates() -> None:
    doc = claims_to_prov(CLAIMS)
    assert validate_prov(doc) == []


def test_provn_and_json_well_formed() -> None:
    pn = to_prov_n(CLAIMS)
    assert pn.startswith("document")
    assert pn.strip().endswith("endDocument")
    pj = to_prov_json(CLAIMS)
    parsed = json.loads(pj)  # must be valid JSON
    assert parsed["prefix"]["prov"] == "http://www.w3.org/ns/prov#"


def test_cli_with_contract_store(tmp_path: "Path | None" = None) -> None:
    import tempfile
    from sophia_contract.service import SophiaContract

    d = Path(tempfile.mkdtemp())
    contract = SophiaContract(store_dir=d, tracing=False)
    contract.record_claim({"idempotency_key": "k1", "content": "Laozi -> Dao De Jing",
                           "sources": ["wikidata"], "blp_level": "UNCLASSIFIED"})
    claims = contract.claims.all_claims()
    assert len(claims) == 1
    doc = claims_to_prov(claims)
    assert validate_prov(doc) == []
    assert any(e == "sophia:source.wikidata" for e in doc["entity"])


def main() -> int:
    import inspect
    for nm, fn in sorted(globals().items()):
        if nm.startswith("test_") and inspect.isfunction(fn):
            fn()
    print("test_prov_export: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
