#!/usr/bin/env python3
"""C1 promotion-gate tests: the real v2 adapter must auto-reject (reproducing the
failure-ledger decision), a clean improving adapter must promote, and the independent
formal protected-floor proof must agree."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.continual_plasticity import Goal, evaluate_update, evaluate_update_multigoal  # noqa: E402
from tools.promote_adapter import (  # noqa: E402
    _formal_protected_floor_proof,
    _parse_goals,
    _retention_from_shift_report,
    _rung,
    build_candidate,
)


def _ladder(base: dict[str, float], adapter: dict[str, float]) -> dict:
    def rung(name: str, doms: dict[str, float]) -> dict:
        passed = sum(round(v * 9) for v in doms.values())
        total = 9 * len(doms)
        return {
            "rung": name,
            "summary": {
                "domains": {k: {"score_pct": round(v * 100, 1)} for k, v in doms.items()},
                "score_pct": round(100 * passed / total, 1),
                "passed": passed,
                "total": total,
            },
        }
    return {"rungs": [rung("base", base), rung("adapter", adapter)]}


def test_v2_adapter_rejects_on_religion_regression() -> None:
    """Gate logic: an adapter that collapses a protected domain (religion -> 0.0) must be
    rejected on the protected-floor rule.

    Built from a synthetic ladder so the test exercises the gate rule directly and stays
    decoupled from the regenerated ``eval_ladder_adapter.json`` artifact, whose scores
    drift between eval runs (it has since moved religion off 0.0, which would silently
    invalidate a brittle artifact-pinned assertion).

    The adapter is deliberately the *faithful hard case*: it clears the target-suite
    improvement floor (total +8.3pp) yet collapses the protected ``religion`` domain to
    0.0 — so the reject must be attributable to the protected-floor rule alone, not to a
    failure to improve. The test asserts exactly that."""
    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.33}
    adapter = {"philosophy": 0.88, "psychology": 0.77, "history": 0.77, "religion": 0.0}
    ladder = _ladder(base, adapter)
    after = _rung(ladder, "adapter")
    assert after is not None and after["domains"]["religion"] == 0.0  # the protected-domain collapse

    cand = build_candidate(
        candidate_id="local-sophia-v2-mlx", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=ladder, contaminated=False, protected=("religion", "history"),
        extra_artifacts=("a", "b"), proof_tag="formal_verifier:protected_floor[fallback:rejected]",
    )[0]
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d.verdict == "reject"
    assert any("religion" in r for r in d.reasons)                       # rejected for the protected regression
    assert not any("below floor" in r for r in d.reasons)                # and NOT because it failed to improve


def test_clean_improving_adapter_promotes() -> None:
    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.33}
    adapter = {"philosophy": 0.77, "psychology": 0.66, "history": 0.66, "religion": 0.44}
    ladder = _ladder(base, adapter)
    cand = build_candidate(
        candidate_id="clean-v1", kind="lora_adapter", baseline_ladder=None, adapter_ladder=ladder,
        contaminated=False, protected=("religion", "history"),
        extra_artifacts=("ladder", "manifest"), proof_tag="formal_verifier:protected_floor[fallback:accepted]",
    )[0]
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d.verdict == "promote", d.reasons


def test_v3_adapter_rejects_under_retention_gate() -> None:
    """An adapter that clears the ladder-only gate (improves, no protected regression) but
    whose real learning-shift report shows a -50pp old-task regression must be rejected by
    the retention-aware gate.

    Uses a synthetic *promotable* ladder rather than reading
    ``training/local_sophia_v2/eval_ladder_adapter.json``: that artifact is regenerated by
    each training run (the v3 convergence pass since moved religion into a protected
    regression), so binding the test to it makes it track whatever adapter ran last and
    masks the retention property this test exists to prove."""
    import json
    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.33}
    adapter = {"philosophy": 0.77, "psychology": 0.66, "history": 0.66, "religion": 0.44}
    shift = json.loads(
        (ROOT / "agi-proof/learning-under-shift/"
                "shift-result-local-sophia-v3-mlx-2026-06-24.public-report.json").read_text()
    )
    cand = build_candidate(
        candidate_id="local-sophia-v3-mlx", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=_ladder(base, adapter), contaminated=False, protected=("religion", "history"),
        extra_artifacts=("a", "b"), proof_tag="formal_verifier:protected_floor[fallback:accepted]",
    )[0]
    retention = _retention_from_shift_report(shift, source="shift")
    # Without retention evidence the ladder-only gate promotes (the historical verdict).
    assert evaluate_update(cand, target_suite="total", min_target_delta=0.03).verdict == "promote"
    # With the real shift report attached, the same adapter is rejected for forgetting.
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, retention=retention)
    assert d.verdict == "reject"
    assert any("retention regression" in r for r in d.reasons)


def test_parse_goals_and_multigoal_promotion() -> None:
    """--goal parsing + a multi-goal Pareto promotion over a real-shaped ladder."""
    goals = _parse_goals(["religion:0.1", "philosophy", "history:0"], default_min_delta=0.03)
    assert goals == (Goal("religion", 0.1), Goal("philosophy", 0.03), Goal("history", 0.0))

    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.167}
    adapter = {"philosophy": 0.77, "psychology": 0.66, "history": 0.66, "religion": 0.5}
    cand = build_candidate(
        candidate_id="mg-v1", kind="lora_adapter", baseline_ladder=None, adapter_ladder=_ladder(base, adapter),
        contaminated=False, protected=("religion", "history"),
        extra_artifacts=("ladder", "manifest"), proof_tag="formal_verifier:protected_floor[fallback:accepted]",
    )[0]
    d = evaluate_update_multigoal(cand, goals=(Goal("religion", 0.10), Goal("philosophy", 0.0)))
    assert d.verdict == "promote", d.reasons
    assert all(g["clearedFloor"] for g in d.metrics["goals"])


def test_formal_proof_agrees_with_scorecard() -> None:
    # protected regression -> formal proof rejects; clean -> accepts
    bad = build_candidate(
        candidate_id="bad", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=_ladder({"history": 0.6, "religion": 0.5}, {"history": 0.6, "religion": 0.0}),
        contaminated=False, protected=("religion", "history"), extra_artifacts=(), proof_tag="",
    )[0]
    assert _formal_protected_floor_proof(list(bad.metrics), tolerance=0.01)["verdict"] == "rejected"

    good = build_candidate(
        candidate_id="good", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=_ladder({"history": 0.6, "religion": 0.5}, {"history": 0.6, "religion": 0.6}),
        contaminated=False, protected=("religion", "history"), extra_artifacts=(), proof_tag="",
    )[0]
    assert _formal_protected_floor_proof(list(good.metrics), tolerance=0.01)["verdict"] == "accepted"


def test_promotion_gate_generalizes_to_non_provenance_families() -> None:
    """Hurdle 2 — the SAME promotion gate works on coding/math families with a
    configurable protected set, not just the provenance suites."""
    # A coding+math adapter that improves both, with NO provenance protected suite.
    base = {"coding": 0.40, "math": 0.50}
    adapter = {"coding": 0.70, "math": 0.75}
    ladder = _ladder(base, adapter)
    cand = build_candidate(
        candidate_id="transfer-coding-math", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=ladder, contaminated=False, protected=(),  # empty protected set
        extra_artifacts=("ladder", "manifest"), proof_tag="formal_verifier:protected_floor[fallback:accepted]",
    )
    # Empty protected set -> the formal proof has nothing to constrain -> accepted.
    assert _formal_protected_floor_proof(list(cand.metrics), tolerance=0.01)["status"] == "no_protected_suites"
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d.verdict == "promote", d.reasons

    # Now mark coding protected and regress it -> the same gate rejects, no provenance involved.
    regress = _ladder({"coding": 0.70, "math": 0.50}, {"coding": 0.40, "math": 0.75})
    cand2 = build_candidate(
        candidate_id="transfer-coding-regress", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=regress, contaminated=False, protected=("coding",),
        extra_artifacts=("a", "b"), proof_tag="",
    )
    d2 = evaluate_update(cand2, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d2.verdict == "reject"
    assert any("coding" in r for r in d2.reasons)


def main() -> int:
    test_v2_adapter_rejects_on_religion_regression()
    test_clean_improving_adapter_promotes()
    test_v3_adapter_rejects_under_retention_gate()
    test_parse_goals_and_multigoal_promotion()
    test_formal_proof_agrees_with_scorecard()
    test_promotion_gate_generalizes_to_non_provenance_families()
    print("test_promote_adapter: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
