#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Tests for tools.audit_cpqa_recall — deterministic source-sufficiency classifier.

Verifies the prose detector ignores the provenance scaffold (`#`/`-`/`>`/`_` lines) and
only counts real sentences, and that a stub page is flagged thin while a page with a real
paragraph is answer-bearing. Offline, deterministic, dependency-free.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.audit_cpqa_recall import classify_source, freeform_prose_lines  # noqa: E402
from okf.page import Page  # noqa: E402

_STUB = """# analects (論語)

- **Attributed author:** confucius_school (confidence: `compiled`)
- **Domain:** philosophy

> **Do not attribute to:** confucius.
_Provenance frontmatter is authoritative; generated by tools/wiki_sync.py._
"""

_RICH = _STUB + (
    "\nThe Analects is a compiled record of conversations attributed to Confucius and his "
    "disciples, assembled by later followers over more than a century after his death.\n"
)


def _page(pid, body):
    return Page(path=Path(f"{pid}.md"), meta={"id": pid, "pageType": "text"}, body=body)


def test_prose_detector_ignores_scaffold() -> None:
    # Only template lines -> no prose.
    assert freeform_prose_lines(_STUB) == []
    # A real sentence is detected.
    prose = freeform_prose_lines(_RICH)
    assert len(prose) == 1 and "compiled record" in prose[0]


def test_stub_is_thin_rich_is_answer_bearing() -> None:
    assert classify_source(_page("analects", _STUB))["answerBearing"] is False
    rich = classify_source(_page("analects", _RICH))
    assert rich["answerBearing"] is True
    assert rich["proseChars"] >= 60


def test_short_prose_below_threshold_is_thin() -> None:
    body = _STUB + "\nFestinger 1957.\n"   # too short to be answer-bearing
    assert classify_source(_page("x", body))["answerBearing"] is False


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print(f"ok {name}")
    print("all passed")
