#!/usr/bin/env python3
"""C1 promotion-gate tests: the real v2 adapter must auto-reject (reproducing the
failure-ledger decision), a clean improving adapter must promote, and the independent
formal protected-floor proof must agree."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.continual_plasticity import evaluate_update  # noqa: E402
from tools.promote_adapter import (  # noqa: E402
    _formal_protected_floor_proof,
    _rung,
    build_candidate,
)


def _ladder(base: dict[str, float], adapter: dict[str, float]) -> dict:
    def rung(name: str, doms: dict[str, float]) -> dict:
        passed = sum(round(v * 9) for v in doms.values())
        total = 9 * len(doms)
        return {
            "rung": name,
            "summary": {
                "domains": {k: {"score_pct": round(v * 100, 1)} for k, v in doms.items()},
                "score_pct": round(100 * passed / total, 1),
                "passed": passed,
                "total": total,
            },
        }
    return {"rungs": [rung("base", base), rung("adapter", adapter)]}


def test_v2_adapter_rejects_on_religion_regression() -> None:
    """The promotion gate must auto-reject a protected-domain (religion) regression,
    reproducing the v2 failure-ledger decision.

    Uses a synthetic v2-shaped ladder (religion regressed 0.33 -> 0.0) instead of
    reading training/local_sophia_v2/eval_ladder_adapter.json, because that on-disk
    file is regenerated by later convergence passes (e.g. the v3 run lifted religion
    to 0.167), which would otherwise silently invalidate this fixed-intent test.
    """
    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.33}
    adapter = {"philosophy": 0.77, "psychology": 0.66, "history": 0.66, "religion": 0.0}  # religion regressed
    adapter_ladder = _ladder(base, adapter)
    after = _rung(adapter_ladder, "adapter")
    assert after is not None and after["domains"]["religion"] == 0.0  # the modelled regression

    cand = build_candidate(
        candidate_id="local-sophia-v2-mlx", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=adapter_ladder, contaminated=False, protected=("religion", "history"),
        extra_artifacts=("a", "b"), proof_tag="formal_verifier:protected_floor[fallback:rejected]",
    )
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d.verdict == "reject"
    assert any("religion" in r for r in d.reasons)


def test_clean_improving_adapter_promotes() -> None:
    base = {"philosophy": 0.66, "psychology": 0.44, "history": 0.62, "religion": 0.33}
    adapter = {"philosophy": 0.77, "psychology": 0.66, "history": 0.66, "religion": 0.44}
    ladder = _ladder(base, adapter)
    cand = build_candidate(
        candidate_id="clean-v1", kind="lora_adapter", baseline_ladder=None, adapter_ladder=ladder,
        contaminated=False, protected=("religion", "history"),
        extra_artifacts=("ladder", "manifest"), proof_tag="formal_verifier:protected_floor[fallback:accepted]",
    )
    d = evaluate_update(cand, target_suite="total", min_target_delta=0.03, max_protected_regression=0.01)
    assert d.verdict == "promote", d.reasons


def test_formal_proof_agrees_with_scorecard() -> None:
    # protected regression -> formal proof rejects; clean -> accepts
    bad = build_candidate(
        candidate_id="bad", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=_ladder({"history": 0.6, "religion": 0.5}, {"history": 0.6, "religion": 0.0}),
        contaminated=False, protected=("religion", "history"), extra_artifacts=(), proof_tag="",
    )
    assert _formal_protected_floor_proof(list(bad.metrics), tolerance=0.01)["verdict"] == "rejected"

    good = build_candidate(
        candidate_id="good", kind="lora_adapter", baseline_ladder=None,
        adapter_ladder=_ladder({"history": 0.6, "religion": 0.5}, {"history": 0.6, "religion": 0.6}),
        contaminated=False, protected=("religion", "history"), extra_artifacts=(), proof_tag="",
    )
    assert _formal_protected_floor_proof(list(good.metrics), tolerance=0.01)["verdict"] == "accepted"


def main() -> int:
    test_v2_adapter_rejects_on_religion_regression()
    test_clean_improving_adapter_promotes()
    test_formal_proof_agrees_with_scorecard()
    print("test_promote_adapter: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
