#!/usr/bin/env python3
"""Generate .cbmignore from the authoritative git-crypt boundary in .gitattributes.

.cbmignore excludes from indexing every filter=git-crypt path (so a git-crypt
file is never indexed even on an unlocked tree) and re-includes the whitelisted
plaintext process skills. Regenerated every run so a NEW secret path (new IP
skill, new docs/superpowers spec, new .grok agent) is covered automatically by
following the RULE in .gitattributes, never a hand-copied name list.

Defense-in-depth ONLY. The load-bearing public-exposure guarantee is L1 locked
preflight + L2 un-committable sink + L3 no-key-in-CI. Gitignored secrets are
additionally excluded by the tool's own .gitignore-respect; a short extras list
backstops the non-git-crypt ones.
"""
from __future__ import annotations
import os
import sys
from pathlib import Path

INDEX_SINKS = [".codebase-memory/", "graph.db*", "*.db.zst"]
SECRET_EXTRAS = [".env", ".env.*", "*.key", "*.pem", "private/"]
HEADER = ("# GENERATED by tools/cbm/derive_cbmignore.py — DO NOT EDIT.\n"
          "# Source of truth: .gitattributes (filter=git-crypt) + index sinks.\n")


def parse_gitattributes(text: str) -> tuple[list[str], list[str]]:
    # NOTE: classifies by the literal `filter=git-crypt` token in the attribute
    # list; assumes no [attr] macro indirection (macro aliases would need separate
    # expansion to resolve the underlying filter value).
    encrypted: list[str] = []
    whitelisted: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        glob, attrs = parts[0], parts[1:]
        if "filter=git-crypt" in attrs:
            encrypted.append(glob)
        elif "!filter" in attrs:
            whitelisted.append(glob)
    return encrypted, whitelisted


def derive(gitattributes_text: str) -> str:
    encrypted, whitelisted = parse_gitattributes(gitattributes_text)
    lines = [HEADER.rstrip("\n"),
             "# --- filter=git-crypt paths (excluded from indexing) ---",
             *encrypted]
    if whitelisted:
        lines += ["# --- plaintext process-skill whitelist (re-included) ---",
                  *(f"!{g}" for g in whitelisted)]
    lines += ["# --- non-git-crypt gitignored secrets (backstop) ---", *SECRET_EXTRAS,
              "# --- index sinks ---", *INDEX_SINKS]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    # CBM_ROOT_OVERRIDE lets the test drive --check against a controlled tmp repo
    # (with its own .gitattributes/.cbmignore); default resolves the repo from __file__.
    _override = os.environ.get("CBM_ROOT_OVERRIDE")
    root = Path(_override).resolve() if _override else Path(__file__).resolve().parents[2]
    content = derive((root / ".gitattributes").read_text())
    target = root / ".cbmignore"
    if "--check" in argv:
        current = target.read_text() if target.exists() else ""
        if current != content:
            sys.stderr.write("ERROR: .cbmignore is stale vs .gitattributes. "
                             "Run: python tools/cbm/derive_cbmignore.py\n")
            return 1
        return 0
    target.write_text(content)
    sys.stdout.write(f"wrote {target}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
