#!/usr/bin/env bash
# Delete branches already fully merged into main (content preserved in main).
# Generated by consolidation pass on 2026-06-26. Run locally where you have push rights.
#   bash scripts/delete-merged-branches.sh
set -euo pipefail
git fetch origin --prune
for b in \
  agi-validation \
  chore/math-code-sft-workflow-on-main \
  ci/parallel-runpod-seeds \
  claude/agi-pilots-feasibility-review-nkoqn3 \
  claude/consolidate-sessions-merge-main-96ld0x \
  claude/continual-learning-catastrophic-forgetting-kyhui2 \
  claude/error-memory-rag \
  claude/fix-promote-adapter-religion-floor-test \
  claude/github-portfolio-redesign-sk5htt \
  claude/gitignore-private-files-q4ljon \
  claude/hk-bilingual-advisor \
  claude/hurdle1-truthfulqa-codex \
  claude/llm-wiki-agi-expansion-v0eifa \
  claude/market-driven-roadmap-04qci9 \
  claude/repo-dev-recommendations-c1zxvy \
  claude/safe-rsi-brainstorm-v7q5f9 \
  claude/sophia-7b-train-verify \
  claude/sophia-agi-architecture-review-ucvzyl \
  claude/sophia-agi-challenges-j4sj7a \
  claude/sophia-agi-feasibility-eval-kzei9d \
  claude/sophia-agi-handover-merge-kkvjji \
  claude/sophia-agi-hurdles-10iqob \
  claude/sophia-consolidation-inventory-vj5wfm \
  claude/sophia-math-code-curriculum \
  claude/sophia-team-orchestrator \
  claude/sophia-training-next-steps-ij1kvm \
  claude/sophia-v3-gate-analysis-w2lyt4 \
  claude/supercomputing-cluster-job-fdbkks \
  claude/team-agents-mode \
  claude/tool-use-training-impl \
  claude/tool-use-training-plan \
  claude/verifier-as-reward-foundation \
  feat/activation-steering-pif \
  feat/capability-retention-mcp \
  feat/personality-council-pif \
  feat/roadmap-to-10 \
  ; do
  echo "deleting $b"; git push origin ":$b" || echo "  (failed: $b)"
done
