#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Generate the math/physics verification dashboard (self-contained HTML).

Renders ``docs/math-physics/index.html`` from the committed result artifacts:

  * ``agi-proof/benchmark-results/published-results.json``  (validated verifier-evals)
  * ``agi-proof/benchmark-results/misstep-bench.json``      (catch-rate by error type)
  * ``agi-proof/benchmark-results/ladder-eval.json``        (per-tier outcome mix)
  * ``agi-proof/benchmark-results/abstention-integrity.json`` (frontier abstention)
  * ``agi-proof/benchmark-results/math-physics-external.json`` (external-style accuracy)

Charts are **inline SVG** — no JavaScript, no CDN, no network — so the page is
deterministic and byte-stable, which lets ``--check`` act as a CI drift gate the
same way ``tools/build_results_page.py --check`` guards RESULTS.md. Like RESULTS.md
this file is GENERATED; never hand-edit it, always regenerate.

    python tools/build_math_physics_dashboard.py            # write the page
    python tools/build_math_physics_dashboard.py --check    # CI: fail if stale
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "agi-proof" / "benchmark-results"
OUT = ROOT / "docs" / "math-physics" / "index.html"

_COLORS = {"verifiedCorrect": "#2e7d32", "rejected": "#c62828", "abstained": "#f9a825"}


def _load(name: str) -> dict:
    p = BENCH / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def _esc(s: object) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def _bar_chart(title: str, rows: list[tuple[str, float]], *, unit: str = "%") -> str:
    """A horizontal SVG bar chart; values are fractions in [0,1] rendered as %."""
    w, rh, pad, label_w = 520, 26, 8, 150
    h = pad * 2 + rh * len(rows)
    bars = []
    for i, (label, frac) in enumerate(rows):
        y = pad + i * rh
        bw = max(0.0, min(1.0, frac)) * (w - label_w - 60)
        pct = f"{frac * 100:.1f}{unit}"
        bars.append(
            f'<text x="0" y="{y + 16}" class="lbl">{_esc(label)}</text>'
            f'<rect x="{label_w}" y="{y + 4}" width="{bw:.1f}" height="16" rx="3" fill="#1565c0"/>'
            f'<text x="{label_w + bw + 6:.1f}" y="{y + 16}" class="val">{pct}</text>'
        )
    return (f'<figure><figcaption>{_esc(title)}</figcaption>'
            f'<svg viewBox="0 0 {w} {h}" width="100%" role="img">{"".join(bars)}</svg></figure>')


def _stacked_chart(title: str, tiers: list[dict]) -> str:
    """Per-tier stacked bars of outcome mix (verifiedCorrect/rejected/abstained)."""
    w, rh, pad, label_w = 560, 30, 10, 180
    h = pad * 2 + rh * len(tiers)
    span = w - label_w - 40
    rows = []
    for i, t in enumerate(tiers):
        y = pad + i * rh
        n = max(1, t.get("n", 0))
        x = label_w
        seg = []
        for key in ("verifiedCorrect", "rejected", "abstained"):
            frac = t.get(key, 0) / n
            sw = frac * span
            if sw > 0:
                seg.append(f'<rect x="{x:.1f}" y="{y + 4}" width="{sw:.1f}" height="18" fill="{_COLORS[key]}"/>')
                x += sw
        label = f"L{t.get('tier')} {t.get('tierName', '')}"
        rows.append(
            f'<text x="0" y="{y + 18}" class="lbl">{_esc(label)}</text>{"".join(seg)}'
            f'<text x="{x + 6:.1f}" y="{y + 18}" class="val">VSC {t.get("meanVSC", 0):.2f}</text>'
        )
    legend = (' '.join(
        f'<span class="key"><i style="background:{c}"></i>{k}</span>'
        for k, c in _COLORS.items()))
    return (f'<figure><figcaption>{_esc(title)}</figcaption>'
            f'<svg viewBox="0 0 {w} {h}" width="100%" role="img">{"".join(rows)}</svg>'
            f'<div class="legend">{legend}</div></figure>')


def render() -> str:
    pub = _load("published-results.json")
    misstep = _load("misstep-bench.json")
    ladder = _load("ladder-eval.json")
    abst = _load("abstention-integrity.json")
    ext = _load("math-physics-external.json")

    L: list[str] = []
    L.append("<!-- GENERATED by tools/build_math_physics_dashboard.py — do not edit by hand. -->")
    L.append('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">')
    L.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    L.append("<title>Sophia — Math/Physics Verification Benchmark</title>")
    L.append("<style>"
             "body{font:15px/1.5 system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#222}"
             "h1{font-size:1.5rem}h2{font-size:1.15rem;margin-top:2rem;border-bottom:1px solid #ddd;padding-bottom:.2rem}"
             ".lbl{font-size:12px;fill:#333}.val{font-size:11px;fill:#555}"
             "figure{margin:1rem 0}figcaption{font-weight:600;margin-bottom:.3rem}"
             ".legend{font-size:12px;color:#555}.key{margin-right:1rem}.key i{display:inline-block;width:10px;height:10px;margin-right:4px;border-radius:2px}"
             "table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #ddd;padding:.3rem .5rem;text-align:left}"
             ".cards{display:flex;gap:1rem;flex-wrap:wrap}.card{flex:1;min-width:150px;background:#f5f7fa;border-radius:6px;padding:.8rem}"
             ".card b{display:block;font-size:1.6rem}.note{color:#666;font-size:12px}.tag{background:#e3f2fd;border-radius:3px;padding:0 .3rem;font-size:11px}"
             "</style></head><body>")
    L.append("<h1>Sophia — Critical Math/Physics Reasoning, every step verified</h1>")
    L.append('<p class="note">Proof-carrying calculation: an answer is accepted only when '
             "<b>every step is machine-verified</b> (sympy symbolic equivalence + SI dimensional analysis), "
             "otherwise the system abstains (fail-closed). The research-frontier tier targets honest "
             "abstention, never &ldquo;solved&rdquo;. <span class=\"tag\">canClaimAGI: false</span></p>")

    # Summary cards
    cards = []
    if misstep:
        cards.append(f'<div class="card"><b>{(misstep.get("misstepCatchRecall") or 0) * 100:.0f}%</b>'
                     f'misstep-catch recall<br><span class="note">N={misstep.get("n")}, '
                     f'{misstep.get("falseAlarmRate", 0) * 100:.0f}% false-alarm</span></div>')
    if abst:
        cards.append(f'<div class="card"><b>{(abst.get("abstentionIntegrity") or 0) * 100:.0f}%</b>'
                     f'abstention integrity<br><span class="note">N={abst.get("n")} open problems, '
                     f'0 fabricated proofs</span></div>')
    if ladder:
        tiers = ladder.get("tiers", [])
        cards.append(f'<div class="card"><b>{len(tiers)}</b>difficulty tiers<br>'
                     f'<span class="note">L1 grade-school &rarr; L6 frontier</span></div>')
    if cards:
        L.append('<div class="cards">' + "".join(cards) + "</div>")

    # Validated verifier-evals
    L.append("<h2>Validated verifier-evals (deterministic, no LLM judge)</h2>")
    rows = pub.get("verifierEvals", [])
    if rows:
        L.append("<table><tr><th>Verifier</th><th>Benchmark</th><th>N</th><th>Accuracy</th>"
                 "<th>Catch recall</th><th>False-alarm</th><th>Date</th></tr>")
        for e in rows:
            def _p(x): return f"{x * 100:.1f}%" if isinstance(x, (int, float)) else "—"
            L.append(f"<tr><td><code>{_esc(e.get('verifier'))}</code></td><td>{_esc(e.get('benchmark'))}</td>"
                     f"<td>{_esc(e.get('n'))}</td><td>{_p(e.get('accuracy'))}</td>"
                     f"<td>{_p(e.get('fabricationDetectionRecall'))}</td><td>{_p(e.get('falseAlarmRate'))}</td>"
                     f"<td>{_esc(e.get('date'))}</td></tr>")
        L.append("</table>")

    # Misstep catch by error type
    if misstep.get("catchByErrorType"):
        bars = [(t, v.get("recall") or 0.0) for t, v in sorted(misstep["catchByErrorType"].items())]
        L.append("<h2>Misstep catch-rate by error type</h2>")
        L.append(_bar_chart("fraction of injected missteps flagged", bars))

    # Ladder stacked bars
    if ladder.get("tiers"):
        L.append("<h2>Difficulty ladder — outcome mix per tier</h2>")
        if ladder.get("illustrative"):
            L.append('<p class="note">⚠ proposer=<code>answer-only</code>: a deterministic harness-validation '
                     "baseline (feeds gold back). Outcome counts are <b>illustrative</b>, not a capability claim. "
                     "Run <code>--proposer model</code> with ≥3 seeds for a real result.</p>")
        L.append(_stacked_chart("verified-correct / rejected / abstained (with mean Verified-Step Coverage)",
                                ladder["tiers"]))

    # External-style accuracy
    if ext.get("sets"):
        L.append("<h2>External-style accuracy (oracle-graded)</h2>")
        if ext.get("illustrative"):
            L.append('<p class="note">⚠ illustrative harness baseline (answer-only). Style samples, '
                     "NOT the licensed MATH/GSM8K sets — see oracle-split.md.</p>")
        L.append("<table><tr><th>Set</th><th>Domain</th><th>N</th><th>Accuracy</th><th>Abstained</th></tr>")
        for s in ext["sets"]:
            acc = f"{s['accuracy'] * 100:.1f}%" if s.get("accuracy") is not None else "—"
            L.append(f"<tr><td>{_esc(s['set'])}</td><td>{_esc(s['domain'])}</td><td>{_esc(s['n'])}</td>"
                     f"<td>{acc}</td><td>{_esc(s.get('abstained'))}</td></tr>")
        L.append("</table>")

    L.append('<p class="note">Pre-registration: '
             "<code>agi-proof/math-physics-verify/preregistration.json</code>. "
             "Reproduce: <code>python tools/run_misstep_bench.py</code>, "
             "<code>run_ladder_eval.py</code>, <code>run_abstention_integrity.py</code>.</p>")
    L.append("</body></html>")
    return "\n".join(L) + "\n"


def main(argv: "list[str] | None" = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = ap.parse_args(argv)

    html = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != html:
            print("math-physics dashboard is STALE — run: python tools/build_math_physics_dashboard.py")
            return 1
        print("math-physics dashboard is up to date.")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
