#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Generate the Leiden-aligned Tool & Computational Resource Disclosure.

The Leiden Declaration on AI and Mathematics asks every researcher to include a
"Tool and computational resource disclosure" section in their work, and to affirm
that credit and responsibility belong to humans, not to automated systems. This
repository operationalizes that ask: instead of a hand-written paragraph that
silently drifts, the disclosure is GENERATED from auditable sources and
drift-checked in CI (same posture as RESULTS.md / the RAG index / the wiki).

Two sources feed it:
  * machine-derived — trained base models from ``training/adapters/registry.jsonl``
    and live tool servers from ``.mcp.json``;
  * declared        — development AI assistants, proprietary measurement services,
    and metered compute providers from ``agi-proof/tool-disclosure.json`` (the
    parts that cannot be derived from code).

    python tools/build_tool_disclosure.py            # write docs/TOOL-DISCLOSURE.md
    python tools/build_tool_disclosure.py --check     # exit 1 if the file is stale

Pure stdlib, deterministic, offline.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "training" / "adapters" / "registry.jsonl"
MCP = ROOT / ".mcp.json"
DECLARED = ROOT / "agi-proof" / "tool-disclosure.json"
OUT = ROOT / "docs" / "TOOL-DISCLOSURE.md"


def _load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _trained_models() -> list[dict]:
    """Distinct base models the project trains adapters on, from the registry."""
    seen: dict[str, dict] = {}
    if not REGISTRY.exists():
        return []
    for ln in REGISTRY.read_text(encoding="utf-8").splitlines():
        ln = ln.strip()
        if not ln:
            continue
        try:
            e = json.loads(ln)
        except Exception:
            continue
        base = e.get("base_model")
        if not base:
            continue
        rec = seen.setdefault(base, {"base_model": base, "methods": set(), "adapters": 0})
        if e.get("method"):
            rec["methods"].add(str(e["method"]))
        rec["adapters"] += 1
    out = []
    for base in sorted(seen):
        rec = seen[base]
        out.append({"base_model": base, "methods": sorted(rec["methods"]),
                    "adapters": rec["adapters"]})
    return out


def _mcp_servers() -> list[dict]:
    data = _load_json(MCP)
    servers = data.get("mcpServers", {}) if isinstance(data, dict) else {}
    out = []
    for name in sorted(servers):
        cfg = servers[name] or {}
        cmd = " ".join([str(cfg.get("command", ""))] + [str(a) for a in cfg.get("args", [])]).strip()
        out.append({"name": name, "command": cmd})
    return out


def _section(title: str, rows: list[str]) -> list[str]:
    out = [f"## {title}", ""]
    out.extend(rows if rows else ["_None declared._"])
    out.append("")
    return out


def render() -> str:
    declared = _load_json(DECLARED)
    lines: list[str] = []
    lines += [
        "<!-- GENERATED FILE — do not edit by hand.",
        "     Source: agi-proof/tool-disclosure.json + training/adapters/registry.jsonl + .mcp.json",
        "     Regenerate: python tools/build_tool_disclosure.py   (CI runs --check) -->",
        "# Tool &amp; Computational Resource Disclosure",
        "",
        "_Generated by `tools/build_tool_disclosure.py`. This section implements the "
        + "Leiden Declaration on AI and Mathematics' call for a tool and computational "
        + "resource disclosure. See [LEIDEN-ALIGNMENT.md](LEIDEN-ALIGNMENT.md)._",
        "",
        "> **Authorship & responsibility.** AI systems listed here are *tools*. "
        + "Credit and responsibility for every result in this repository remain with the "
        + "human maintainer; no result is attributed to an automated system. "
        + "`canClaimAGI: false` everywhere.",
        "",
    ]

    # Machine-derived: trained models
    rows = []
    for m in _trained_models():
        methods = ", ".join(m["methods"]) or "—"
        rows.append(f"- **{m['base_model']}** — method(s): {methods}; "
                    f"{m['adapters']} adapter entr{'y' if m['adapters'] == 1 else 'ies'} "
                    f"(from `training/adapters/registry.jsonl`)")
    lines += _section("Trained / fine-tuned base models", rows)

    # Machine-derived: MCP tool servers
    rows = [f"- **{s['name']}** — `{s['command']}`" for s in _mcp_servers()]
    lines += _section("Tool servers (MCP, from `.mcp.json`)", rows)

    # Declared: development assistants
    rows = []
    for a in declared.get("development_assistants", []):
        tag = " _(proprietary)_" if a.get("proprietary") else " _(open)_"
        note = f" — {a['note']}" if a.get("note") else ""
        rows.append(f"- **{a.get('name')}**{tag} — {a.get('role', '')}{note}")
    lines += _section("AI assistants used during development", rows)

    # Declared: measurement services
    rows = []
    for s in declared.get("measurement_services", []):
        tag = " _(proprietary)_" if s.get("proprietary") else " _(open)_"
        note = f" — {s['note']}" if s.get("note") else ""
        rows.append(f"- **{s.get('name')}**{tag} — {s.get('role', '')}{note}")
    lines += _section("Measurement / judge inference services", rows)

    # Declared: compute providers
    rows = []
    for c in declared.get("compute_providers", []):
        tag = " _(proprietary)_" if c.get("proprietary") else " _(open)_"
        note = f" — {c['note']}" if c.get("note") else ""
        rows.append(f"- **{c.get('name')}**{tag} — {c.get('role', '')}{note}")
    lines += _section("Metered compute providers", rows)

    lines += [
        "---",
        "",
        "_Proprietary tools are marked; the project prefers open, non-proprietary "
        + "alternatives and owned hardware where feasible (a Leiden Declaration "
        + "recommendation). Known gaps in non-proprietary coverage are tracked in "
        + "[LEIDEN-ALIGNMENT.md](LEIDEN-ALIGNMENT.md)._",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/TOOL-DISCLOSURE.md is missing or stale")
    args = ap.parse_args(argv)

    content = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("TOOL DISCLOSURE: STALE — run `python tools/build_tool_disclosure.py` "
                  "and commit docs/TOOL-DISCLOSURE.md")
            return 1
        print("TOOL DISCLOSURE: OK — docs/TOOL-DISCLOSURE.md is up to date.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
