#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Data asset registry — the missing catalog over all committed data manifests.

Phase 1 of docs/11-Platform/Data-Analysis-Agent-Strategy.md. The repo already emits
per-shard / per-benchmark manifests, but there is no single queryable index of "what
corpora exist, their size, sealed/disjoint status, and a content anchor". This builds
that catalog deterministically from the committed manifests, so humans and the Data
Analysis Agent stop doing git archaeology, and so the DHI ``lineage`` dimension has a
real source.

Each asset carries a ``manifestSha256`` (sha256 of the manifest file bytes) — the
lineage/reproducibility anchor: if a manifest changes without the registry being
rebuilt, ``--check`` fails in CI.

    python tools/build_data_registry.py            # write the registry JSON
    python tools/build_data_registry.py --check     # CI: exit 1 if the registry is stale

Determinism: pure stdlib, sorted iteration, no timestamps.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "agi-proof" / "data-health" / "registry.json"
MANIFEST_GLOBS = ("data/*/manifest.json", "training/*/manifest.json")
SCHEMA = "sophia.data_registry.v1"
HASH_FIELDS = ("contentHash", "embeddingsSha256", "sha256")


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _rows_of(doc: dict) -> int:
    """Best-effort row/case count from heterogeneous manifest shapes."""
    if "nCases" in doc:
        return int(doc.get("nCases", 0))
    totals = doc.get("totals") or {}
    if "accepted" in totals:
        return int(totals.get("accepted", 0))
    mlx = doc.get("mlx") or {}
    if "trainRows" in mlx:
        return int(mlx.get("trainRows", 0)) + int(mlx.get("validRows", 0))
    return 0


def _kind_of(rel_parent: str, doc: dict) -> str:
    if doc.get("sealed") or rel_parent.endswith("_benchmark"):
        return "benchmark"
    if rel_parent.startswith("training/"):
        return "training"
    return "dataset"


def build_registry() -> dict:
    manifests: list[Path] = []
    for g in MANIFEST_GLOBS:
        manifests.extend(ROOT.glob(g))
    assets: list[dict] = []
    for mp in sorted(set(manifests)):
        try:
            doc = json.loads(mp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        rel_parent = mp.parent.relative_to(ROOT).as_posix()
        content_hash = next((doc.get(f) for f in HASH_FIELDS if doc.get(f)), None)
        assets.append({
            "path": rel_parent,
            "manifest": mp.relative_to(ROOT).as_posix(),
            "schema": doc.get("schema"),
            "id": doc.get("datasetId") or doc.get("benchmarkId") or rel_parent.split("/")[-1],
            "kind": _kind_of(rel_parent, doc),
            "rows": _rows_of(doc),
            "sealed": bool(doc.get("sealed", False)),
            "trainingDisjoint": bool(doc.get("trainingDisjoint", False)),
            "candidateOnly": bool(doc.get("candidateOnly", False)),
            "contentHash": content_hash,
            "manifestSha256": _sha256_file(mp),
        })
    assets.sort(key=lambda a: a["path"])
    summary = {
        "nAssets": len(assets),
        "nSealed": sum(1 for a in assets if a["sealed"]),
        "nWithContentHash": sum(1 for a in assets if a["contentHash"]),
        "byKind": {
            k: sum(1 for a in assets if a["kind"] == k)
            for k in sorted({a["kind"] for a in assets})
        },
    }
    return {
        "schema": SCHEMA,
        "note": "Generated by tools/build_data_registry.py — do not edit by hand.",
        "canClaimAGI": False,
        "summary": summary,
        "assets": assets,
    }


def serialize(reg: dict) -> str:
    return json.dumps(reg, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed registry is stale")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args(argv)

    reg = build_registry()
    rendered = serialize(reg)

    if args.check:
        if not args.out.exists():
            print(f"DATA REGISTRY: FAIL — {args.out.relative_to(ROOT)} missing; run tools/build_data_registry.py")
            return 1
        if args.out.read_text(encoding="utf-8") != rendered:
            print("DATA REGISTRY: FAIL — committed registry is stale; re-run tools/build_data_registry.py")
            return 1
        print(f"DATA REGISTRY: OK — {reg['summary']['nAssets']} assets current")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"DATA REGISTRY: wrote {args.out.relative_to(ROOT)} — {reg['summary']['nAssets']} assets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
