#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Carve an entity-disjoint held-out candidate using the entity auditor as oracle.

Phase 3 of docs/11-Platform/Data-Analysis-Agent-Strategy.md. The SEIB-100 split is
contaminated because contested entities leak across the train/eval boundary
(failure-ledger ``seib-generalization-split-not-validated``). This tool uses
``tools/assert_entity_decontam`` as an oracle to classify every eval prompt as:

  * **disjoint**     — none of its known entities appear in any training prompt, AND
                       it carries at least one recognised entity (a real, attributable
                       probe, not an entity-free filler line);
  * **contaminated** — shares ≥1 entity with training;
  * **no-entity**    — carries no recognised entity (can't certify either way).

The disjoint set is a genuinely entity-disjoint held-out CANDIDATE. The tool is
**dry-run by default** — it never mutates the committed eval surfaces; with ``--out``
it writes the candidate as JSONL plus a manifest with a content hash and the
disjointness proof (sharedWithTrain == 0).

    python tools/carve_entity_disjoint_split.py                       # report only
    python tools/carve_entity_disjoint_split.py --json                # machine-readable
    python tools/carve_entity_disjoint_split.py --out data/seib_entity_disjoint/candidate.jsonl

Determinism: sorted iteration, content-hashed output, no timestamps.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from provenance_bench.dataset_guard import eval_prompt_set  # noqa: E402
from tools.assert_entity_decontam import (  # noqa: E402
    build_entity_vocab, entities_in, _train_prompts)


def carve() -> dict:
    vocab = build_entity_vocab()
    train_entities: set[str] = set()
    for pr in _train_prompts():
        train_entities |= entities_in(pr, vocab)

    disjoint: list[dict] = []
    contaminated = 0
    no_entity = 0
    for pr in sorted(eval_prompt_set(root=ROOT)):
        ents = entities_in(pr, vocab)
        if not ents:
            no_entity += 1
            continue
        if ents & train_entities:
            contaminated += 1
        else:
            disjoint.append({"prompt": pr, "entities": sorted(ents)})

    disjoint.sort(key=lambda d: d["prompt"])
    # disjointness proof: the union of all candidate entities must not meet train.
    cand_entities: set[str] = set()
    for d in disjoint:
        cand_entities |= set(d["entities"])
    shared_with_train = sorted(cand_entities & train_entities)

    return {
        "schema": "sophia.entity_disjoint_split.v1",
        "candidateOnly": True,
        "canClaimAGI": False,
        "nTrainEntities": len(train_entities),
        "nEvalTotal": disjoint_total(disjoint, contaminated, no_entity),
        "nDisjoint": len(disjoint),
        "nContaminated": contaminated,
        "nNoEntity": no_entity,
        "sharedWithTrain": shared_with_train,        # MUST be [] for a valid carve
        "disjoint": disjoint,
    }


def disjoint_total(disjoint, contaminated, no_entity) -> int:
    return len(disjoint) + contaminated + no_entity


def _disp(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def serialize_manifest(result: dict, jsonl: str) -> str:
    manifest = {
        "schema": result["schema"],
        "candidateOnly": True,
        "canClaimAGI": False,
        "trainingDisjoint": result["sharedWithTrain"] == [],
        "nCases": result["nDisjoint"],
        "sharedWithTrain": result["sharedWithTrain"],
        "nTrainEntitiesGuardedAgainst": result["nTrainEntities"],
        "contentHash": hashlib.sha256(jsonl.encode("utf-8")).hexdigest(),
        "note": "Generated by tools/carve_entity_disjoint_split.py — entity-disjoint held-out CANDIDATE.",
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", action="store_true", help="emit the machine-readable report")
    ap.add_argument("--out", type=Path, default=None,
                    help="write the candidate JSONL (+ sibling manifest.json); default is dry-run")
    args = ap.parse_args(argv)

    result = carve()
    valid = result["sharedWithTrain"] == []

    if args.json:
        summary = {k: v for k, v in result.items() if k != "disjoint"}
        print(json.dumps(summary, indent=2, ensure_ascii=False))
    else:
        print(f"CARVE: evalTotal={result['nEvalTotal']} -> disjoint={result['nDisjoint']} "
              f"contaminated={result['nContaminated']} noEntity={result['nNoEntity']}")
        print(f"  disjointness proof: sharedWithTrain={len(result['sharedWithTrain'])} "
              f"({'VALID' if valid else 'INVALID'})")

    if args.out is not None:
        if not valid:
            print("REFUSE — carve is not entity-disjoint; not writing.")
            return 1
        jsonl = "".join(json.dumps(d, ensure_ascii=False, sort_keys=True) + "\n" for d in result["disjoint"])
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(jsonl, encoding="utf-8")
        man = args.out.parent / "manifest.json"
        man.write_text(serialize_manifest(result, jsonl), encoding="utf-8")
        print(f"  wrote {_disp(args.out)} ({result['nDisjoint']} cases) + {_disp(man)}")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
