#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Sophia Skill Forge: task -> verifier -> skill -> eval suite -> registration.

Input spec JSON:
{
  "task_id": "danger",
  "description": "detect destructive intent",
  "examples": [{"text": "delete db", "label": true}, ["read db", false]]
}

The forge uses the strong ``agent.verifier_synthesis`` path through
``gateway.skill_flywheel.synthesize_gate``. Optional LLM-proposed predicates are
AST-sandboxed and must clear held-out validation before promotion.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.verifier_proposer import make_model_proposer  # noqa: E402
from gateway import Gateway, ToolEntry  # noqa: E402
from gateway.skill_flywheel import synthesize_gate  # noqa: E402

OUT_ROOT = ROOT / "skills" / "generated"
REGISTRY_INDEX = ROOT / "skills" / "registry" / "forge_index.json"


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "skill").lower()).strip("-") or "skill"


def _pairs(spec: dict) -> list[tuple[str, bool]]:
    out = []
    for item in spec.get("examples", []):
        if isinstance(item, dict):
            text = item.get("text") or item.get("answer") or item.get("input") or item.get("query") or ""
            label = item.get("label", item.get("accepted", item.get("positive", False)))
            out.append((str(text), bool(label)))
        elif isinstance(item, (list, tuple)) and len(item) >= 2:
            out.append((str(item[0]), bool(item[1])))
    return out


def _candidate_manifest(res) -> list[dict]:
    rows = []
    for cand, stats in res.admitted:
        rows.append({
            "name": cand.name,
            "params": cand.params,
            "validation": {"precision": stats.precision, "recall": stats.recall, "accuracy": stats.accuracy, "n": stats.n},
        })
    return rows


def _write_json(path: Path, obj: dict | list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str) + "\n", encoding="utf-8")


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except Exception:
        return str(path)


def _inside_repo(path: Path) -> bool:
    try:
        path.resolve().relative_to(ROOT)
        return True
    except Exception:
        return False


def _registry_load(path: Path = REGISTRY_INDEX) -> dict:
    if not path.exists():
        return {"schema": "sophia.skill_forge.registry.v1", "skills": []}
    return json.loads(path.read_text(encoding="utf-8"))


def _registry_upsert(record: dict, *, path: Path = REGISTRY_INDEX) -> dict:
    """Append/update a generated-skill registry entry.

    The registry is the promotion ledger for Skill Forge: every promoted skill
    records its verifier evidence and eval surface, so Gateway exposure can be
    audited rather than becoming an untracked file drop.
    """
    registry = _registry_load(path)
    skills = [r for r in registry.get("skills", []) if r.get("skill_id") != record.get("skill_id")]
    now = datetime.now(timezone.utc).isoformat()
    record = dict(record)
    record.setdefault("registered_at", now)
    record["updated_at"] = now
    skills.append(record)
    skills.sort(key=lambda r: r.get("skill_id", ""))
    registry["skills"] = skills
    registry["updated_at"] = now
    _write_json(path, registry)
    return registry


def _write_skill_files(skill_dir: Path, spec: dict, manifest: dict, examples: list[tuple[str, bool]]) -> None:
    skill_dir.mkdir(parents=True, exist_ok=True)
    _write_json(skill_dir / "manifest.json", manifest)
    _write_json(skill_dir / "promotion_report.json", manifest["promotion"])
    with (skill_dir / "eval_suite.jsonl").open("w", encoding="utf-8") as f:
        for text, label in examples:
            f.write(json.dumps({"args": {"text": text}, "expect": bool(label)}, ensure_ascii=False) + "\n")

    verifier_py = f'''# Generated by tools/sophia_skill_forge.py. Do not edit by hand.
from __future__ import annotations
import re
from agent.verifier_synthesis import _compile_predicate, _is_prime

RULES = {json.dumps(manifest["rules"], indent=2, ensure_ascii=False, default=str)}


def _num(x):
    try:
        if isinstance(x, bool):
            return None
        return float(str(x).strip())
    except Exception:
        return None


def _one(rule, answer) -> bool:
    name = rule.get("name", "")
    params = rule.get("params", {{}}) or {{}}
    text = str(answer)
    if name.startswith("contains:"):
        return str(params.get("token") or name.split(":", 1)[1]).lower() in text.lower()
    if name.startswith("regex:"):
        return bool(re.search(str(params.get("pattern", ".^")), text))
    if name == "length_range":
        return int(params.get("lo", 0)) <= len(text) <= int(params.get("hi", 10**9))
    if name == "in_range":
        n = _num(answer); return n is not None and float(params.get("lo")) <= n <= float(params.get("hi"))
    if name == "is_integer":
        n = _num(answer); return n is not None and float(n).is_integer()
    if name == "positive":
        n = _num(answer); return n is not None and n > 0
    if name == "nonneg":
        n = _num(answer); return n is not None and n >= 0
    if name.startswith("divisible_by_"):
        n = _num(answer); k = int(params.get("k", name.rsplit("_", 1)[-1])); return n is not None and float(n).is_integer() and int(n) % k == 0
    if name == "is_prime":
        n = _num(answer); return n is not None and float(n).is_integer() and _is_prime(int(n))
    if name.startswith("proposed:") and params.get("src"):
        fn = _compile_predicate(params["src"])
        return bool(fn(answer)) if fn else False
    return False


def check_answer(answer) -> bool:
    return any(_one(rule, answer) for rule in RULES) if RULES else False
'''
    (skill_dir / "verifier.py").write_text(verifier_py, encoding="utf-8")

    skill_py = '''# Generated Sophia verifiable skill.
from __future__ import annotations
from verifier import check_answer


def run(args: dict) -> dict:
    text = str(args.get("text") or args.get("query") or args.get("input") or "")
    return {"answer": bool(check_answer(text)), "sources": ["skillforge://" + __name__]}
'''
    (skill_dir / "skill.py").write_text(skill_py, encoding="utf-8")

    readme = f'''# {manifest["skill_id"]}

Generated Sophia Skill Forge skill.

- Description: {spec.get("description", "")}
- Promotion: meta-verified verifier synthesis; unvalidated candidates rejected.
- Verifier: `verifier.py`
- Program: `skill.py`
- Eval suite: `eval_suite.jsonl`

Use through Sophia Gateway so outputs remain provenance-stamped and gated.
'''
    (skill_dir / "SKILL.md").write_text(readme, encoding="utf-8")


def _load_generated_program(skill_dir: Path):
    spec = importlib.util.spec_from_file_location("generated_skill", skill_dir / "skill.py")
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load generated skill from {skill_dir}")
    module = importlib.util.module_from_spec(spec)
    # Make same-dir verifier import work for this smoke registration.
    sys.path.insert(0, str(skill_dir))
    try:
        spec.loader.exec_module(module)
    finally:
        try:
            sys.path.remove(str(skill_dir))
        except ValueError:
            # path entry may already have been removed; nothing to clean up
            pass
    return module.run


def forge_skill(
    spec: dict,
    *,
    out_root: Path = OUT_ROOT,
    threshold: float = 0.8,
    seed: int = 1,
    proposer_model: str = "mock",
    gateway: Gateway | None = None,
    update_registry: bool = True,
) -> dict:
    task_id = _slug(str(spec.get("task_id") or spec.get("id") or "skill"))
    examples = _pairs(spec)
    propose_fn = make_model_proposer(proposer_model) if proposer_model and proposer_model != "off" else None
    promoted, res = synthesize_gate(task_id, examples, threshold=threshold, seed=seed, propose_fn=propose_fn)
    skill_id = f"skill.{task_id}"
    skill_dir = out_root / task_id
    # Unit tests and ad-hoc experiments often forge into /tmp. Do not pollute
    # the committed registry with temp paths; the registry tracks repo-local
    # generated skills that Gateway can discover later.
    update_registry = bool(update_registry and _inside_repo(skill_dir))
    promotion = {"promoted": promoted, **res.report()}
    if not promoted:
        skill_dir.mkdir(parents=True, exist_ok=True)
        _write_json(skill_dir / "promotion_report.json", promotion)
        if update_registry:
            _registry_upsert({
                "skill_id": skill_id,
                "task_id": task_id,
                "description": spec.get("description", ""),
                "skill_dir": _display_path(skill_dir),
                "promotion_status": "rejected",
                "promotion": promotion,
            })
        return {"created": False, "skill_id": skill_id, "skill_dir": str(skill_dir), "promotion": promotion}

    rules = _candidate_manifest(res)
    manifest = {
        "skill_id": skill_id,
        "task_id": task_id,
        "description": spec.get("description", ""),
        "verifier_ref": "grounding",
        "source": "skillforge",
        "threshold": threshold,
        "seed": seed,
        "rules": rules,
        "promotion": promotion,
    }
    _write_skill_files(skill_dir, spec, manifest, examples)

    registered = None
    eval_report = None
    if gateway is not None:
        program = _load_generated_program(skill_dir)
        entry = gateway.register(ToolEntry(
            id=skill_id,
            handler=program,
            kind="skill",
            verifier_ref="grounding",
            side_effects="none",
            description=f"Skill Forge generated skill: {spec.get('description', task_id)}",
        ))
        registered = entry.public(gateway.competence.reliability(entry.id))
        # Smoke-eval through gateway.
        total = accepted = correct = 0
        for text, label in examples:
            total += 1
            r = gateway.call_tool(skill_id, {"text": text})
            accepted += int(r.get("verdict") == "accepted")
            if r.get("verdict") == "accepted":
                correct += int(bool((r.get("result") or {}).get("answer")) == bool(label))
        eval_report = {"total": total, "accepted": accepted, "correct": correct,
                       "accuracy": round(correct / total, 4) if total else None}

    registry_record = None
    if update_registry:
        best_validation = None
        if rules:
            best_validation = max((r.get("validation", {}) for r in rules), key=lambda x: x.get("accuracy", 0), default={})
        registry_record = {
            "skill_id": skill_id,
            "task_id": task_id,
            "description": spec.get("description", ""),
            "skill_dir": _display_path(skill_dir),
            "verifier_ref": manifest["verifier_ref"],
            "source": "skillforge",
            "promotion_status": "accepted",
            "threshold": threshold,
            "seed": seed,
            "rule_count": len(rules),
            "best_validation": best_validation,
            "eval_suite": _display_path(skill_dir / "eval_suite.jsonl"),
            "promotion": promotion,
            "smoke_eval": eval_report,
        }
        _registry_upsert(registry_record)

    return {"created": True, "skill_id": skill_id, "skill_dir": str(skill_dir),
            "rules": rules, "promotion": promotion, "registered": registered,
            "eval": eval_report, "registry": registry_record}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("spec", type=Path, help="task spec JSON")
    ap.add_argument("--out-root", type=Path, default=OUT_ROOT)
    ap.add_argument("--threshold", type=float, default=0.8)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--proposer-model", default="mock", help="mock|off|deepseek|openrouter:... etc")
    ap.add_argument("--register-smoke", action="store_true", help="register in a fresh Gateway and run eval smoke test")
    ap.add_argument("--no-registry", action="store_true", help="do not update skills/registry/forge_index.json")
    args = ap.parse_args(argv)
    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    gw = Gateway() if args.register_smoke else None
    out = forge_skill(spec, out_root=args.out_root, threshold=args.threshold, seed=args.seed,
                      proposer_model=args.proposer_model, gateway=gw,
                      update_registry=not args.no_registry)
    print(json.dumps(out, indent=2, ensure_ascii=False, default=str))
    return 0 if out.get("created") else 1


if __name__ == "__main__":
    raise SystemExit(main())
